### ISSUE TITLE
vac

### ISSUE THREAD

**Issue by TDekkerDev** [tsuriga/csgo-gsi-qsguide#4]
can you gat vac?

**Comment by tsuriga** [comment]
Game State Integration is just a built-in way of relaying information that happens in the game to a listener. That listener can (but does not have to) be situated on another system that doesn't interact with your gaming system. For setting up a configuration file for GSI alone no, you cannot get VAC banned. I cannot speak for any other software you run on your gaming system alongside the GSI configuration.
